########## GUIDE ##########
# (1) Please do not change
# (2) Do not change as we use the same bucket for all poc deployments
# (3) Note the prefix <subdirectory name> for the key (distinguishing different poc deployments)
# (4) Should always be poc-model-deployment/<subdirectory name>
# (5) Please do not change (shared among poc deployments)
# (6) This should be unique for each poc deployment
########## GUIDE ##########
app:
  container:
    image: PLACEHOLDER # (1)
    run_time:
      env:
        - name: S3_BUCKET # S3 bucket where artifacts are located (required)
          value: science-poc-model-deployment # (2)
        - name: S3_KEY # S3 key for the model artifact (optional)
          value: <subdirectory name>/A/B/... # (3)
        - name: ROOT_PATH # ROOT PATH for the FastAPI application (required)
          value: poc-model-deployment/<subdirectory name> # (4)
        # Add more env variables depending on what you need at runtime (e.g., folder in s3 where your artifacts are located)
      secrets: [] # Add if the container needs it at runtime. Otherwise, set `secrets: []`
        # Add more secrets
  port_mapping: 
    port: 8080 # (5)
routing: # ALB listener rule
  priority: <integer> # (6)